### ISSUE TITLE
Alpha Test

### ISSUE THREAD

**Issue by Spacelord-XaN** [braunau-mobil/velo-basar#215]
## Warnings
- [x] Microsoft.EntityFrameworkCore.Query[20504]
      Compiling a query which loads related collections for more than one collection navigation, either via 'Include' or through projection, but no 'QuerySplittingBehavior' has been configured. By default, Entity Framework will use 'QuerySplittingBehavior.SingleQuery', which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'.

## Bugs:
- [x] To long Product Description (without spaces) breaks Layout:
Menu dissapears

## Server
- [x] create new brands does not work => Sequences in the DB are broken
- [x] Am Server bzw. Basar mit HTTP arbeiten, damit wir die Zertifikatsprobleme nicht haben
- [x] Neu aufsetzen
- [x] Struktur schön machen

## ToDo
- [x] Display "Annahme fortsetzen" instead of "Neue Annahme" when Acceptance is running
- [x] ReadMe
- [x] Token wieder auf altes Format umstellen (VB prefix weglassen), eventuell mit einer GUID speichern und danach updaten??
- [x] Configuration überarbeiten
- [x] Deployment am Server als fertige Binaries
- [x] Use State for Seller, check State for other Entities
- [x] Check if HTML Table can break content that is too long
